### ISSUE TITLE
Feature Request: Support for HELM Linting

### ISSUE THREAD

**Issue by rdeveen** [Azure/k8s-lint#44]
### Feature request

Hi, I wonder why this action doesn't support Helm Lint? To validate the Helm charts? 

https://helm.sh/docs/helm/helm_lint/

**Comment by OliverMKing** [comment]
Hi @rdeveen. Thanks for the suggestion. This action is purely for k8s manifests. You may want to look into Helm testing and its corresponding [action](https://github.com/helm/chart-testing-action) so you can both lint and validate Helm charts.
