### ISSUE TITLE
Update to Node 16+

### ISSUE THREAD

**Issue by MarcusFelling** [Azure/k8s-lint#45]
### What happened?

Node.js 12 actions are deprecated. More info here: [https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). 

Please update this action to use Node.js 16 to make these annoying annotations go away! 🤣

![image](https://user-images.githubusercontent.com/6855361/223761080-1d4bd2ec-e98e-4133-833b-dce951b86424.png)

### Version

- [X] I am using the latest version

### Runner

ubuntu-latest

### Relevant log output

![image](https://user-images.githubusercontent.com/6855361/223761225-552fd859-3181-4177-8487-68de36a83094.png)

**Comment by OliverMKing** [comment]
Hi @MarcusFelling. We will create the release today.

**Comment by MarcusFelling** [comment]
Hi @OliverMKing - I wanted to check in and see if you could create a new release. No rush, this is mostly a nit pick as it's the last GHA in our repo with this warning 🙂

**Comment by rdeveen** [comment]
> Hi @MarcusFelling. We will create the release today.

Did I miss this release? We still get this warning when using this action.

**Comment by davidgamero** [comment]
release was made here https://github.com/Azure/k8s-lint/releases/tag/v3.0.0
